name: Auto PR Commentor
author: The Robot

branding:
  icon: 'award'
  color: 'green'


runs:
  using: "composite"
  steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - name: Add comment
        run: gh pr comment "$NUMBER" --repo "$REPO" --body "$BODY" --edit-last
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NUMBER: ${{ github.event.pull_request.number }}
            REPO: ${{ github.repository }}
            BODY: >
                LOOK MA! I am a comment! $NOW